### ISSUE TITLE
 Update `argo-controller` manifests 

### ISSUE THREAD

**Issue by misohu** [canonical/argo-operators#166]
### Context

Each charm has a set of manifest files that have to be upgraded to their target version. The process of upgrading manifest files usually means going to the component’s upstream repository, comparing the charm’s manifest against the one in the repository and adding the missing bits in the charm’s manifest.

### What needs to get done

https://docs.google.com/document/d/1a4obWw98U_Ndx-ZKRoojLf4Cym8tFb_2S7dq5dtRQqs/edit?pli=1#heading=h.jt5e3qx0jypg

### Definition of Done

1. Manifests are updated 
2. Upstream image is used

**Comment by orfeas-k** [comment]
While working in KFP, there were some changes in argo-related manifests, which we do not include in KFP. When updating argo, we should make sure that updates here are in terms with changes in KFP. Pasting here the changes for reference:

<details><summary>Diff</summary>

* Adding CRD workfloweventbindings.argoproj.io
* Change in CRD workflows.argoproj.io
* Changes in CRD workflowtaskresults.argoproj.io
* Change in argo-cluster-role
```diff
>   - workflowartifactgctasks
```
* Change in workflow-controller-configmap
```diff
<   containerRuntimeExecutor: emissary
```
* Removal of workflow-controller-metrics `Service`
* Bump of argo images
```diff
<         - gcr.io/ml-pipeline/argoexec:v3.3.10-license-compliance
---
>         - gcr.io/ml-pipeline/argoexec:v3.4.16-license-compliance
<         image: gcr.io/ml-pipeline/workflow-controller:v3.3.10-license-compliance
---
>         image: gcr.io/ml-pipeline/workflow-controller:v3.4.16-license-compliance
```

</details>

**Comment by DnPlas** [comment]
Thanks @orfeas-k for the context!

* #169 introduces all necessary changes on the CRDs, but if there is anything missing, please let me know
* I will remove all Roles and ClusterRoles in #168. The reason is explained in that PR and in the associated issue.
* I have removed the runtime executor, let's also make sure that is removed from the config options
* We were not applying the `workflow-controller-metrics Service`, so I don't think we need to do anything about this
* I believe #169 will cover all the image bumps, but let me know if that is not the case
